#!/bin/bash

OFFICIAL=(
    intel-ucode
    uv
    yadm
    audacity
    d2
    dbeaver
    git-lfs
    handbrake
    lact
    libreoffice-fresh-ru
    obs-studio
    qbittorrent
    rocminfo
    telegram-desktop
    zed
)

AUR=(
    anytype-bin
    deadbeef
    happ-desktop-bin
    visual-studio-code-bin
)

sudo pacman -S --needed --noconfirm "${OFFICIAL[@]}"
paru -S --needed --noconfirm --skipreview "${AUR[@]}"
paru -S --needed --noconfirm --skipreview \
    --overwrite '*' ffmpeg-amd-full
