autofit-larger=92%x92%
autofit-smaller=50%x50%
geometry=50%:50%
auto-window-resize=yes
save-position-on-quit=yes

cursor-autohide=200

hdr-compute-peak=yes
target-colorspace-hint=yes
gpu-api=vulkan
hwdec=vulkan
scale=ewa_lanczossharp
dscale=ewa_lanczossharp
dither-depth=no

glsl-shaders="~~/shaders/FSRCNNX_x2_16-0-4-1.glsl:~~/shaders/adaptive-sharpen.glsl"
